### ISSUE TITLE
A problem on the windows: Method `diff_paths` outputs the opposite result on different os.

### ISSUE THREAD

**Issue by zong-zhe** [Manishearth/pathdiff#10]
I had this problem while migrating our program from macos to windows.

I've simplified the bad code to look like this:
```
fn main() {
    let root = "/home/config";

    let dirpath = "path/to/app";

    match pathdiff::diff_paths(dirpath, root) {

        // On windows, it will println.
        Some(s) => {println!("{}", s.display().to_string())},

       // On macos, it will panic.
        None => {panic!()},

    }
}
```

**Comment by zong-zhe** [comment]
version info:
```
pathdiff = "0.2.1"

macos = Ventura 13.1
windows = Microsoft Windows [version 10.0.19045.2251]
```

**Comment by Manishearth** [comment]
https://doc.rust-lang.org/stable/std/path/struct.Path.html

The Path API that this is based on requires using the right kind of slash for paths on different platforms. You can construct them from components instead if you want to be agnostic.
