### ISSUE TITLE
Docs fail to build on docs.rs since last release

### ISSUE THREAD

**Issue by t4lz** [Manishearth/pathdiff#14]
This is what I currently see at https://docs.rs/crate/pathdiff/0.2.2
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/aba41970-d29f-41af-baf3-a1850aa98e6b">

Build logs:
https://docs.rs/crate/pathdiff/0.2.2/builds/1388304

**Comment by Manishearth** [comment]
Published 0.2.3. Thanks for flagging this!
