### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bglw** [Manishearth/pathdiff#6]
Test `tests::test_absolute` fails on Windows

**Comment by sunshowers** [comment]
@bglw thanks! looks like it was just a test issue and not a bug in the code, I've fixed it in #7.

**Comment by bglw** [comment]
Nice 😄 

I presume I hit an error that led me to this, but I can't recall what that error was and I believe I'm using it with success on Windows now. So if anything is wrong it's my fault for providing absolutely no details in this issue 😅 

Thanks! I'll open a new issue if I hit anything tangible.
